name: Build and release RPM repository
run-name: Build and release RPM repository (${{ github.ref_type }}=${{ github.ref_name }})

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - client/**
      - cmd/**
      - internal/**
      - lib/** 
      - vendor/**
      - mocks/**
      - Makefile
      - go.mod
      - go.sum

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  build-and-release-rpm:
    runs-on: self-hosted  # Since GitHub Actions doesn't offer CentOS runners, you need to use self-hosted runners
    env:
      ENV: "prod"
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.PROD_BUILD_AND_DEPLOY_ROLE }}
          role-session-name: BuildAndDeploy4border0cli
          role-duration-seconds: 1800 # 30 minutes

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1' # The Go version to download (if necessary) and use.
      - run: go version

      - name: Generate git repo version string
        run: |
          BORDER0_VERSION=$(git describe --long --dirty --tags)
          echo ${BORDER0_VERSION}
          echo "BORDER0_VERSION=${BORDER0_VERSION}" >> $GITHUB_ENV

      - name: Install required packages
        run: |
            sudo yum update -y
            sudo yum install -y gnupg make rpm-build rpm-sign rpmdevtools createrepo

      - name: Import PGP Key
        run: |
            echo "${PGP_PRIVATE_KEY}" | gpg --import

      - name: where am i?
        run: |
          gpg -k
          pwd
          ls

      - name: Run Make all
        run: |
            make all

      - name: Run Make build-linux-amd64
        run: |
            make build-linux-amd64

      - name: Run Make rpm-package-amd64
        run: |
            make rpm-package-amd64

      - name: Run Make rpm-repository
        run: |
            make rpm-repository

      - name: Publish repo to S3 bucket
        run: |
          aws s3 sync ~/rpm/ s3://pub-mysocketctl-bin/rpm/

      - name: Invalidate CloudFront cache for download.border0.com
        run: |
          aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
